[theme]

primaryColor = "#009d6e"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#009d6e"
textColor = "#000000"
baseFontSize = 16
dataframeBorderColor = "#009d6e"
dataframeHeaderBackgroundColor = "#4aedbc"

[theme.sidebar]

backgroundColor =  "#009d6e"
textColor = "#ffffff"
primaryColor = "#000000"
secondaryColor = "#000000"
secondaryBackgroundColor = "#0050a0"


